### ISSUE TITLE
Bot is not working.

### ISSUE THREAD

**Issue by EntityReborn** [Bluscream/BetterDiscord-Plugins-and-Themes#21]
I installed the bot and what I think are it's requirements, but there's no logbot button (as the source appears to mention), there's no other indication that the bot is running.
I am able to show the log window using javascript, but it doesn't update with any entries.

**Comment by Bluscream** [comment]
You should really take a look at the last commit date of this file.

**Comment by EntityReborn** [comment]
Yes, that makes sense. Is there interest in updating this?

**Comment by Bluscream** [comment]
Not really. i suggest using something like https://github.com/appu1232/Discord-Selfbot

https://discord.gg/FGnM5DM

**Comment by EntityReborn** [comment]
Im more looking for something that logs events in my own client than a standalone client, which I think yours did. Thanks anyway.

**Comment by Bluscream** [comment]
@EntityReborn Are we talking about a log or the bot with commands now?

**Comment by EntityReborn** [comment]
Just about the log. I'd like to see text deletions, nick changes, bans, etc.
