### ISSUE TITLE
Account Switcher plugin not showing up

### ISSUE THREAD

**Issue by MeixDev** [Bluscream/BetterDiscord-Plugins-and-Themes#23]
Like said in the title, the AccountSwitcher plugin isn't showing up in the plugin menu.
Is it still on the works or did you let it go ?
Thanks !

**Comment by Bluscream** [comment]
Its outdated

**Comment by Bluscream** [comment]
Update it yourself or ask someone to fix it for you :)

**Comment by MeixDev** [comment]
Thanks for the answer. Have a good day !
