### ISSUE TITLE
Check out my plugins:

### ISSUE THREAD

**Issue by shtrih** [Bluscream/BetterDiscord-Plugins-and-Themes#6]
- https://gist.github.com/shtrih/59a8be1f9ff53f0499c2 — Collapse embeds like in `Slack`
- https://gist.github.com/shtrih/8a72a36d513ec704c7a9 — Embeds video and audio

**Comment by Bluscream** [comment]
Please create a pull request so i can merge them. Thanks for beeing a part of the Discord Enhancers Community btw :D
