### ISSUE TITLE
Broken plugins...

### ISSUE THREAD

**Issue by cosmicsalad** [Bluscream/BetterDiscord-Plugins-and-Themes#7]
Hey man, just posting here to see if you'd be willing to take a good amount of the plugins you have hosted here for BD down. Lots of these plugins haven't been updated in ages and some of them cause a lot of problems for Discord servers. Your BD+ setup exe installs a lot of outdated and buggy plugins and it would probably be better to just remove this.

**Comment by Bluscream** [comment]
I personally would not recommend to use the installer anymore at all. I won't update them cause i can't cause i don't use Discord anymore at all. But if someone creates a PR with a fixed version of a plugin i'm willing to merge it.

**Comment by cosmicsalad** [comment]
Yeah I understand that. I'm mainly just asking if you'd remove the installer and old plugins from your repo here. Just so they don't cause further issues, and since you don't use Discord at all anymore.

**Comment by Bluscream** [comment]
I created https://github.com/Bluscream/BetterDiscord-Plugins-and-Themes/releases/tag/99
